name: 'moomoo'
version: '1.0.32'
config-version: 2
profile: 'moomoo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  materialized: table
  +grants:
    select: ['ro']
  moomoo:
    local_files:
      stg:
        +schema: stg
    analytic:
      materialized: view
