
version: 2


models:
  - name: track_play_spikes
    description: Records of play spikes (cases where one track was played >=5 times in 24h).
    columns:
      - name: start_listen_md5
        tests:
          - not_null
          - unique

  - name: artist_recommends
    description: Recommended artists from similar users.
    columns:
      - name: artist_mbid
        tests:
          - not_null
          - unique

  - name: library_release_additions
    description: |
      Releases which similar users listen to a lot, but which are not in the library already.
      May be good candidates for adding to the library.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - time_range
            - rank
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - release_group_mbid
            - time_range
            - username


  - name: revisit_releases
    description: Albums with historically high listens but not many recent listens.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - release_group_mbid
            - username
    columns:
      - name: release_group_mbid
        tests:
          - not_null
      - name: username
        tests:
          - not_null
      - name: release_group_title
        tests:
          - not_null
      - name: artist_name
        tests:
          - not_null
  
  - name: revisit_tracks
    description: Tracks with historically high listens but not many recent listens.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - recording_mbid
            - username
    columns:
      - name: recording_mbid
        tests:
          - not_null
      - name: username
        tests:
          - not_null
      - name: recording_title
        tests:
          - not_null
      - name: artist_name
        tests:
          - not_null
      - name: filepath
        tests:
          - not_null
      - name: artist_mbid
        tests:
          - not_null

  - name: file_listen_counts
    description: Analytic table of listen data for each file for each user.
    columns:
      - name: filepath_username_id
        tests:
          - unique
          - not_null
      - name: filepath
        tests:
          - not_null
      - name: username
        tests:
          - not_null
      - name: track_name
        tests:
          - not_null
      - name: album_name
        tests:
          - not_null
      - name: artist_name
        tests:
          - not_null
      - name: album_artist_name
      - name: lifetime_listen_count
        tests:
          - not_null
      - name: last07_listen_count
        tests:
          - not_null
      - name: last30_listen_count
        tests:
          - not_null
      - name: last90_listen_count
        tests:
          - not_null
      - name: recency_score
        tests:
          - not_null
      - name: revisit_score
        tests:
          - not_null

  - name: daily_user_listen_stats
    description: Analytic table with listen stats for each user for each day.
    columns:
      - name: user_date_key
        tests:
          - unique
          - not_null
      - name: username
        tests:
          - not_null
      - name: listen_date
        tests:
          - not_null
      - name: count_listens
        tests:
          - not_null
      - name: pct_listens_mapped_to_file
        tests:
          - not_null
      - name: count_recordings
        tests:
          - not_null
      - name: count_releases
        tests:
          - not_null
      - name: sum_listen_hours

  - name: loved_tracks
    description: Tracks that users love. Unions the spikes against the listenbrainz feedback.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - filepath
    columns:
      - name: username
        tests:
          - not_null
      - name: filepath
        tests:
          - not_null
      - name: love_at
        tests:
          - not_null

  - name: playlist_file_counts
    description: Count the number of times a file is currently included across all user playlists.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - username
            - filepath
    columns:
      - name: username
        tests:
          - not_null
      - name: filepath
        tests:
          - not_null
      - name: track_name
      - name: album_name
      - name: artist_name
      - name: album_artist_name
      - name: playlist_count
        tests:
          - not_null
      - name: collection_names