"""Syncronize mooomoo playlists to navidrome."""

from pathlib import Path

import click
from moomoo_pg import PlaylistCollection, get_session

from ..logger import logger
from ..models import MoomooPlaylistSignature
from ..navidrome import NavidromeDBClient, NavidromeHTTPClient

TITLE_PREFIX = "mm |"


def drop_all_moomoo_playlists(client: NavidromeHTTPClient) -> None:
    """Deletes all playlists that have a moomoo signature.

    Returns the number of playlists deleted.
    """
    logger.info("Dropping all moomoo playlists.")
    playlists = client.fetch_playlists()
    moomoo_playlists = [pl for pl in playlists if pl.name.startswith(TITLE_PREFIX)]
    logger.info(f"Found {len(moomoo_playlists)} moomoo playlists to delete.")
    deleted = 0
    for pl in moomoo_playlists:
        logger.info(f"Deleting playlist '{pl.name}' with ID {pl.playlist_id}.")
        client.delete_playlist(pl.playlist_id)
        deleted += 1
    return deleted


def sync_playlists_collection(
    client: NavidromeHTTPClient,
    collection: PlaylistCollection,
    force: bool = False,
) -> None:
    """Replaces all playlists of a specific type with new moomoo definitions."""
    logger.info(f"Starting sync for collection '{collection.collection_name}' playlists.")

    # get the playlists matching the collection name and signature
    playlists = [
        pl
        for pl in client.fetch_playlists()
        if pl.signature is not None and pl.signature.collection_name == collection.collection_name
    ]

    # check if the uuids match those in the collection, can skip if they do

    navi_uuids = {pl.signature.moomoo_playlist_id for pl in playlists}
    collection_uuids = {item.playlist_id for item in collection.items}

    if navi_uuids == collection_uuids and not force:
        logger.info("All playlists are up to date, skipping sync.")
        return

    # delete old playlists
    if playlists:
        logger.info(f"Purging {len(playlists)} old playlists.")
        for pl in playlists:
            client.delete_playlist(pl.playlist_id)

    #  recreate playlists
    logger.info(f"Creating {len(collection.items)} new playlist(s).")
    for item in collection.items:
        playlist_paths = [track.filepath for track in item.tracks]
        song_ids = NavidromeDBClient().get_song_ids(playlist_paths)

        if not song_ids:
            logger.warning(f"No tracks found for {item.collection_order_index}.")

        title = f"{TITLE_PREFIX} {item.description}"
        signature = MoomooPlaylistSignature.from_playlist(item)
        created_at = item.create_at_utc.strftime("%B %d, %H:%M UTC")
        synced_at = signature.signed_at.strftime("%B %d, %H:%M UTC")
        comment = "\n".join(
            [
                f"Collection: {collection.collection_name} #{item.collection_order_index}",
                f"Created: {created_at}, synced: {synced_at}",
                "Generated by: moomoo-navidrome sync_playlists_by_type",
                signature.signature,
            ]
        )
        logger.info(f"Creating playlist '{title}' with {len(song_ids)} tracks.")
        try:
            client.create_playlist(name=title, comment=comment, song_ids=song_ids)
        except Exception:
            logger.exception(f"Failed to create playlist '{title}'.")
            raise


@click.group()
def cli():
    pass


@cli.command()
@click.option("-f", "--force", is_flag=True, help="Force sync even if playlists appear up to date.")
def sync(force: bool):
    with get_session() as session, NavidromeHTTPClient() as client:
        collections = session.query(PlaylistCollection).order_by(PlaylistCollection.collection_name)
        for collection in collections:
            sync_playlists_collection(client=client, collection=collection, force=force)


@cli.command("drop-all")
def drop_all():
    with NavidromeHTTPClient() as client:
        drop_all_moomoo_playlists(client=client)


if __name__ == "__main__":
    cli()
